### ISSUE TITLE
Some items cannot be sold with Sell Wand

### ISSUE THREAD

**Issue by kamber5** [BG-Software-LLC/WildTools#165]
### Minecraft's Version

git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

### Plugin's Version

2023.2

### Describe the bug

In ShopGUIPlus (1.85.0 version) we have gunpowder and magma cream placed for sell. When players are using the Sell Wands on their chests they get a message that there are no items to sell. The gunpowder and magma cream can be in the chest

### To Reproduce

1. Have gunpowder or magma cream for sell in ShopGui+
2. Take any kind of sell wand (uses, infinite)
3. Click on chest
4. You should get the message described above

### Additional Information

- Here is a video of the chest we are selling

![image](https://github.com/BG-Software-LLC/WildTools/assets/35629701/af430820-7c65-4715-bc65-c8cd55119031)

- Here is proof that that item is sellabe

![image](https://github.com/BG-Software-LLC/WildTools/assets/35629701/1d1ece84-8dcd-4b1c-9308-391c57f85e4c)

**Comment by OmerBenGera** [comment]
WildTools uses ShopGUIPlus's API in order to get prices for items.
Therefore, if the prices is not detected, then it might be an issue with ShopGUIPlus, or the way you configured your shop.

Do you mind testing it with default files of both WildTools and ShopGUIPlus, on a server with only these plugins installed (as well as any essential plugin for them to function - for example, Vault and an Economy plugin)

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
