### ISSUE TITLE
Somewhat of a bug regarding POTIONS.

### ISSUE THREAD

**Issue by klaidosHka** [BG-Software-LLC/WildTools#95]
### Minecraft's Version

1.16.5 Paper

### Plugin's Version

Any. But at the memoment latest dev build (b55?).

### Describe the bug

Every potion is the same when using sell wand with ShopGui+ as shop provider. 😩
For example, I have made that almost every potion is sellable for the same price, however Water Potion is not. But people just make glass bottles, put them into a chest and make tons of money, because unsellable item (by /sell command) is being sold for the price of other potions. I don't know if you can fix it anyhow, but would be awesome. Maybe there is a way to blacklist certain items in the chest? Anything like that would probably work too as a roundway...

### To Reproduce

Put an item to the chest that has the same type as other sellable items, but with other metadata and try to sell it with the SellWand. Use ShopGui+ (maybe any other shop provider too).

**Comment by OmerBenGera** [comment]
There is a way to make ShopGUIPlus to "compare metadata" somehow.
If you know what I am talking about, make sure it's enabled for potions in your config.
If you do not know what I talk about, contact their developers regarding the compare-metadata feature and enable it using their help.

Let me know if the issue is fixed afterwards :)

**Comment by klaidosHka** [comment]
Yep, it is fixed, thank you for reminding that. One sad thing about the shop provider and that option would be that there is no whitelist/blacklist, but whatever, as long as it works in a good enough manner ^^
